"""initial schema

Revision ID: bd7beedf1515
Revises: 
Create Date: 2026-08-30 02:57:48.908124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7beedf1515'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('asset_category', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_datetime', sa.DateTime(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('proceeds', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_external_id'), 'executions', ['external_id'], unique=True)
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_symbol'), 'executions', ['symbol'], unique=False)
    op.create_index(op.f('ix_executions_trade_date'), 'executions', ['trade_date'], unique=False)
    op.create_index(op.f('ix_executions_trade_datetime'), 'executions', ['trade_datetime'], unique=False)
    op.create_table('trade_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_trip_id', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_notes_id'), 'trade_notes', ['id'], unique=False)
    op.create_index(op.f('ix_trade_notes_round_trip_id'), 'trade_notes', ['round_trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_notes_round_trip_id'), table_name='trade_notes')
    op.drop_index(op.f('ix_trade_notes_id'), table_name='trade_notes')
    op.drop_table('trade_notes')
    op.drop_index(op.f('ix_executions_trade_datetime'), table_name='executions')
    op.drop_index(op.f('ix_executions_trade_date'), table_name='executions')
    op.drop_index(op.f('ix_executions_symbol'), table_name='executions')
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_external_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
