"""add upload batches

Revision ID: bbb716a14596
Revises: bd7beedf1515
Create Date: 2026-08-30 03:04:32.956139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb716a14596'
down_revision: Union[str, Sequence[str], None] = 'bd7beedf1515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_batches_id'), 'upload_batches', ['id'], unique=False)
    op.add_column('executions', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_executions_batch_id'), 'executions', ['batch_id'], unique=False)
    op.create_foreign_key('fk_executions_batch_id', 'executions', 'upload_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_executions_batch_id', 'executions', type_='foreignkey')
    op.drop_index(op.f('ix_executions_batch_id'), table_name='executions')
    op.drop_column('executions', 'batch_id')
    op.drop_index(op.f('ix_upload_batches_id'), table_name='upload_batches')
    op.drop_table('upload_batches')
    # ### end Alembic commands ###
